version: '3.8'

services:
  # Spring Boot application service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  # MySQL database service
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: novine
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
  # React application service
  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"